#!/bin/bash
SERVICE_NAME='cloudwatch-metrics'
SERVICE_DIR='/var/lib/dpkg/info/cloudwatch-metrics'
if [[ $(pidof -s systemd) ]]
then 
  cp ${SERVICE_DIR}.systemd_config /lib/systemd/system/${SERVICE_NAME}.service
elif [[ $(pidof /sbin/init) ]]
then 
  cp ${SERVICE_DIR}.initd_config /etc/init.d/${SERVICE_NAME}.conf
fi
