#!/bin/bash
SERVICE_NAME='cloudwatch-metrics'
if [[ $(pidof -s systemd) ]]
then 
  systemctl disable ${SERVICE_NAME}.service
  systemctl stop ${SERVICE_NAME}.service
elif [[ $(pidof /sbin/init) ]]
then 
  update-rc.d -f ${SERVICE_NAME} remove
  service stop ${SERVICE_NAME}
fi
